name: Check Required Files

on: [push, pull_request]

jobs:
  check-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run file check script
        run: ./.github/workflows/check-required-files.sh
