name: Count Files in Directory

on:
  pull_request:
    types: [opened, synchronize]  # Run on new pull requests and updates to existing pull requests

jobs:
  count_files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run count-files.sh
        id: count_files
        run: |
          ./count-files.sh .  # Pass the root directory as the argument to count files
        # Save the result to a variable
        id: result
        run: |
          FILE_COUNT=$(./count-files.sh .)
          echo "FILE_COUNT=$FILE_COUNT" >> $GITHUB_ENV

      - name: Comment on PR with the file count
        uses: actions/github-script@v6
        with:
          script: |
            const fileCount = process.env.FILE_COUNT;
            const issueComment = `Number of files in the repository root directory: ${fileCount}`;
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: issueComment
            });
