name: Count Files in Directory fields

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  count-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run count-files script
        run: ./.github/workflows/count-files.sh .

      - name: Upload count result
        uses: actions/upload-artifact@v3
        with:
          name: count-files-result
          path: .github/workflows/count-files-result.txt

      - name: Comment on pull request
        id: comment
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const filePath = '.github/workflows/count-files-result.txt';
            const result = fs.readFileSync(filePath, 'utf8');
            const comment = `**File Count Result:**\n\n${result}`;
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment,
            });

