name: Generate Changelog

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write  # Required to push changes to the repository

jobs:
  changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git fetch --tags

      - name: Ensure script is executable
        run: |
          chmod +x ./generate-changelog.sh

      - name: Run changelog generation script
        run: |
          ./generate-changelog.sh

      - name: Commit and push changelog
        run: |
          git config --global user.name "giridhar552520"
          git config --global user.email "giridharprasad926@gmail.com"
          git add CHANGELOG.md
          git commit -m "Update changelog"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}  # Ensure PAT is configured correctly
