name: Increment Version

on:
  push:
    branches:
      - main
    # Only trigger the workflow on push events that are merges (i.e., not direct pushes or merges from other branches)
    types:
      - merged

jobs:
  increment_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js (Optional)
        uses: actions/setup-node@v3
        with:
          node-version: '14'  # Specify your Node.js version here if needed

      - name: Increment Version
        run: |
          chmod +x ./increment-version.sh
          ./increment-version.sh

      - name: Commit and Push Version Changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add version.txt
          git commit -m "Increment version number"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
